### ISSUE TITLE
AWS에 서버 배포

### ISSUE THREAD

**Issue by secureWKkim** [97zPaleBlueDot/BackEnd#24]
## 어떤 기능인가요?
> 클라우드 환경에 서버 배포 후 이것저것 테스트

## ✅ Task List

- [x] 로컬 백엔드에서 AWS DB 연결 테스트
- [x] Bitnami + Apache 설정 코드 PR+브랜치 올리고 실패 시 git rollback
- [x] 위 브랜치 EC2에 clone 후 클라우드 환경 전체 test
- [x] 위 사항 성공 시 프론트까지 테스트

---

### 💡 고려사항

- ooo

<br>

> #### Reference
> NULL
> - [title](link)
